# Generated by Django 4.0.4 on 2022-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Department',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
